language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - benchmarking
notifications:
  email:
    recipients:
      - esteves@cs.uni-bonn.de
    on_success: change
    on_failure: change
after_success:
  - mvn clean 
